import ExerciseCard from '@/components/ExerciseCard';
import Pagination from '@/components/Pagination';
import { baseUrl, fetchApi } from '@/utils/fetchApi';
import { paginate } from '@/utils/paginationHelper';
import { IExercise } from '@/utils/types';
import { Box, Flex } from '@chakra-ui/react';
import Head from 'next/head';
import { useState } from 'react';

type HomeProps = { exercises: IExercise[] };

export default function Home({ exercises }: HomeProps) {
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 20;

  const paginatedExercises = paginate(exercises, currentPage, pageSize);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="gray.100">
        <Flex flexDirection={'column'} alignItems="center">
          <Flex
            flexWrap="wrap"
            justifyContent="center"
            alignItems="center"
            gap="10px"
          >
            {paginatedExercises.map((exercise: IExercise) => (
              <ExerciseCard key={exercise.id} exercise={exercise} />
            ))}
          </Flex>
          <Pagination
            itemsLength={exercises.length}
            currentPage={currentPage}
            pageSize={pageSize}
            changePage={setCurrentPage}
          />
        </Flex>
      </Box>
    </>
  );
}

export async function getStaticProps() {
  const allExercises = await fetchApi(baseUrl);

  return {
    props: {
      exercises: allExercises,
    },
  };
}
